apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: nginx-test
spec:
  project: default

  source:
    repoURL: https://github.com/randeer/argo-cd.git
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx-test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true