apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test-k8s
  namespace: nginx-test
spec:
  secretName: nginx-test-k8s
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'k8s.lala-1992.xyz'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdata
  namespace: nginx-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: pythonwebapp
        image: randeerdil/wordpressautomation:7.5
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /data  # Mount the volume to the /data directory in the container
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: userdata


---
apiVersion: v1
kind: Service
metadata:
  name:  nginx
  namespace: nginx-test
spec:
  selector:
    app:  nginx
  # ---
  type:  ClusterIP
  ports:
   - name:  http
     port:  80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: nginx-test
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: k8s.lala-1992.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx
            port:
              number: 80
  tls:
  - hosts:
    - k8s.lala-1992.xyz
    secretName: nginx-test-k8s
---
